// 200+ missions organized by category
// Each mission has: sentence (the heist), hint (one word revealed mid-round), category

export const missionsByCategory = {
  india: [
    { sentence: "steal taj mahal blueprint", hint: "taj", category: "india" },
    { sentence: "hack irctc servers", hint: "irctc", category: "india" },
    { sentence: "steal pani puri recipe", hint: "pani", category: "india" },
    { sentence: "kidnap bollywood director", hint: "bollywood", category: "india" },
    { sentence: "replace parliament chairs with beanbags", hint: "parliament", category: "india" },
    { sentence: "steal samosa recipe from vendor", hint: "samosa", category: "india" },
    { sentence: "hack aadhaar database secretly", hint: "aadhaar", category: "india" },
    { sentence: "steal kohinoor diamond back", hint: "kohinoor", category: "india" },
    { sentence: "swap gateway of india with cardboard", hint: "gateway", category: "india" },
    { sentence: "steal chai recipe from roadside stall", hint: "chai", category: "india" },
    { sentence: "replace bollywood songs with silence", hint: "songs", category: "india" },
    { sentence: "hack mumbai traffic signals", hint: "mumbai", category: "india" },
    { sentence: "steal butter chicken secret recipe", hint: "butter", category: "india" },
    { sentence: "kidnap cricket team mascot", hint: "cricket", category: "india" },
    { sentence: "replace holi colors with glitter", hint: "holi", category: "india" },
    { sentence: "steal mysore palace chandelier", hint: "mysore", category: "india" },
    { sentence: "hack delhi metro announcements", hint: "metro", category: "india" },
    { sentence: "steal jalebi recipe from halwai", hint: "jalebi", category: "india" },
    { sentence: "replace auto rickshaw horns with music", hint: "rickshaw", category: "india" },
    { sentence: "steal rangoli design from artist", hint: "rangoli", category: "india" },
    { sentence: "hack doordarshan broadcast signal", hint: "doordarshan", category: "india" },
    { sentence: "steal biryani recipe from hyderabad", hint: "biryani", category: "india" },
  ],
  sports: [
    { sentence: "steal virat kohli bat", hint: "virat", category: "sports" },
    { sentence: "steal ipl trophy from stadium", hint: "ipl", category: "sports" },
    { sentence: "replace football with balloon", hint: "football", category: "sports" },
    { sentence: "hack olympic scoreboard results", hint: "olympic", category: "sports" },
    { sentence: "steal formula one racing car", hint: "formula", category: "sports" },
    { sentence: "kidnap world cup mascot animal", hint: "mascot", category: "sports" },
    { sentence: "replace tennis balls with oranges", hint: "tennis", category: "sports" },
    { sentence: "steal hockey goal post secretly", hint: "hockey", category: "sports" },
    { sentence: "hack cricket pitch sprinkler system", hint: "sprinkler", category: "sports" },
    { sentence: "steal basketball hoop from arena", hint: "basketball", category: "sports" },
    { sentence: "replace marathon finish tape with ribbon", hint: "marathon", category: "sports" },
    { sentence: "steal swimming pool water overnight", hint: "swimming", category: "sports" },
    { sentence: "hack gym treadmill speed controls", hint: "treadmill", category: "sports" },
    { sentence: "steal boxing championship belt secretly", hint: "boxing", category: "sports" },
    { sentence: "replace golf balls with ping pong", hint: "golf", category: "sports" },
    { sentence: "steal referee whistle before match", hint: "referee", category: "sports" },
    { sentence: "hack stadium jumbotron display system", hint: "jumbotron", category: "sports" },
    { sentence: "steal cricket stumps during match", hint: "stumps", category: "sports" },
    { sentence: "replace chess pieces with candy", hint: "chess", category: "sports" },
    { sentence: "steal badminton net from court", hint: "badminton", category: "sports" },
  ],
  food: [
    { sentence: "steal secret pizza dough recipe", hint: "pizza", category: "food" },
    { sentence: "replace sugar with salt everywhere", hint: "sugar", category: "food" },
    { sentence: "steal chocolate factory formula", hint: "chocolate", category: "food" },
    { sentence: "hack restaurant reservation system", hint: "restaurant", category: "food" },
    { sentence: "steal grandma secret cookie recipe", hint: "cookie", category: "food" },
    { sentence: "replace ice cream with mashed potato", hint: "cream", category: "food" },
    { sentence: "steal sushi chef knife collection", hint: "sushi", category: "food" },
    { sentence: "hack food delivery app algorithm", hint: "delivery", category: "food" },
    { sentence: "steal noodle recipe from monastery", hint: "noodle", category: "food" },
    { sentence: "replace coffee beans with chocolate", hint: "coffee", category: "food" },
    { sentence: "steal taco truck secret salsa", hint: "taco", category: "food" },
    { sentence: "hack bakery oven temperature remotely", hint: "bakery", category: "food" },
    { sentence: "steal famous burger sauce formula", hint: "burger", category: "food" },
    { sentence: "replace pasta with rubber noodles", hint: "pasta", category: "food" },
    { sentence: "steal maple syrup from warehouse", hint: "maple", category: "food" },
    { sentence: "hack vending machine snack dispenser", hint: "vending", category: "food" },
    { sentence: "steal dumpling recipe from chef", hint: "dumpling", category: "food" },
    { sentence: "replace wasabi with green frosting", hint: "wasabi", category: "food" },
    { sentence: "steal cake decoration design book", hint: "cake", category: "food" },
    { sentence: "hack cereal factory mixing machine", hint: "cereal", category: "food" },
    { sentence: "steal popcorn butter secret blend", hint: "popcorn", category: "food" },
    { sentence: "replace honey with golden syrup", hint: "honey", category: "food" },
  ],
  technology: [
    { sentence: "hack college attendance system", hint: "attendance", category: "technology" },
    { sentence: "steal robot prototype from lab", hint: "robot", category: "technology" },
    { sentence: "hack satellite navigation system", hint: "satellite", category: "technology" },
    { sentence: "steal quantum computer chip design", hint: "quantum", category: "technology" },
    { sentence: "replace wifi router with toaster", hint: "wifi", category: "technology" },
    { sentence: "hack smart fridge shopping list", hint: "fridge", category: "technology" },
    { sentence: "steal drone delivery package midair", hint: "drone", category: "technology" },
    { sentence: "hack video game leaderboard scores", hint: "leaderboard", category: "technology" },
    { sentence: "steal virtual reality headset prototype", hint: "virtual", category: "technology" },
    { sentence: "replace keyboard keys with candy", hint: "keyboard", category: "technology" },
    { sentence: "hack traffic camera feed downtown", hint: "camera", category: "technology" },
    { sentence: "steal server room cooling system", hint: "server", category: "technology" },
    { sentence: "replace phone charger with spaghetti", hint: "charger", category: "technology" },
    { sentence: "hack smart speaker voice assistant", hint: "speaker", category: "technology" },
    { sentence: "steal startup pitch deck secretly", hint: "startup", category: "technology" },
    { sentence: "hack printer to print memes", hint: "printer", category: "technology" },
    { sentence: "steal laptop from tech conference", hint: "laptop", category: "technology" },
    { sentence: "replace bluetooth signal with static", hint: "bluetooth", category: "technology" },
    { sentence: "hack elevator floor selection buttons", hint: "elevator", category: "technology" },
    { sentence: "steal cryptocurrency mining hardware", hint: "crypto", category: "technology" },
    { sentence: "hack digital billboard advertisements", hint: "billboard", category: "technology" },
    { sentence: "steal ai model training data", hint: "model", category: "technology" },
  ],
  movies: [
    { sentence: "steal oscar trophy from backstage", hint: "oscar", category: "movies" },
    { sentence: "replace movie script with fan fiction", hint: "script", category: "movies" },
    { sentence: "hack cinema projector during premiere", hint: "cinema", category: "movies" },
    { sentence: "steal superhero costume from set", hint: "superhero", category: "movies" },
    { sentence: "kidnap stunt double before action scene", hint: "stunt", category: "movies" },
    { sentence: "replace popcorn machine with confetti", hint: "machine", category: "movies" },
    { sentence: "steal directors chair from studio", hint: "directors", category: "movies" },
    { sentence: "hack streaming platform recommendations", hint: "streaming", category: "movies" },
    { sentence: "steal film reel from movie vault", hint: "reel", category: "movies" },
    { sentence: "replace green screen with wallpaper", hint: "screen", category: "movies" },
    { sentence: "steal camera from documentary crew", hint: "documentary", category: "movies" },
    { sentence: "hack movie theater ticket system", hint: "ticket", category: "movies" },
    { sentence: "steal props from horror movie set", hint: "horror", category: "movies" },
    { sentence: "replace red carpet with banana peels", hint: "carpet", category: "movies" },
    { sentence: "steal film festival award trophy", hint: "festival", category: "movies" },
    { sentence: "hack animation studio render farm", hint: "animation", category: "movies" },
    { sentence: "steal screenplay from famous writer", hint: "screenplay", category: "movies" },
    { sentence: "replace movie soundtrack with kazoo", hint: "soundtrack", category: "movies" },
    { sentence: "steal costume from period drama set", hint: "costume", category: "movies" },
    { sentence: "hack drive in theater radio frequency", hint: "drive", category: "movies" },
  ],
  absurd: [
    { sentence: "steal moon rock from museum display", hint: "moon", category: "absurd" },
    { sentence: "replace ocean water with lemonade", hint: "ocean", category: "absurd" },
    { sentence: "steal tooth from tooth fairy", hint: "tooth", category: "absurd" },
    { sentence: "hack weather forecast to show dragons", hint: "weather", category: "absurd" },
    { sentence: "steal gravity from science laboratory", hint: "gravity", category: "absurd" },
    { sentence: "replace clouds with cotton candy", hint: "clouds", category: "absurd" },
    { sentence: "steal paint from rainbow overnight", hint: "rainbow", category: "absurd" },
    { sentence: "hack alarm clocks worldwide simultaneously", hint: "alarm", category: "absurd" },
    { sentence: "steal shadow from sleeping person", hint: "shadow", category: "absurd" },
    { sentence: "replace homework with blank paper", hint: "homework", category: "absurd" },
    { sentence: "steal dream from sleeping neighbor", hint: "dream", category: "absurd" },
    { sentence: "hack traffic lights to disco mode", hint: "disco", category: "absurd" },
    { sentence: "steal voice from karaoke singer", hint: "karaoke", category: "absurd" },
    { sentence: "replace exam paper with crossword puzzle", hint: "exam", category: "absurd" },
    { sentence: "steal time from all wall clocks", hint: "clocks", category: "absurd" },
    { sentence: "hack school bell to play music", hint: "bell", category: "absurd" },
    { sentence: "steal wifi password from neighbor cat", hint: "password", category: "absurd" },
    { sentence: "replace library books with comics", hint: "library", category: "absurd" },
    { sentence: "steal echo from mountain valley", hint: "echo", category: "absurd" },
    { sentence: "hack doorbell to ring randomly", hint: "doorbell", category: "absurd" },
    { sentence: "steal bubbles from soap factory", hint: "bubbles", category: "absurd" },
    { sentence: "replace sunlight with disco lights", hint: "sunlight", category: "absurd" },
  ],
  crime: [
    { sentence: "steal exam paper from professor", hint: "professor", category: "crime" },
    { sentence: "hack bank vault laser security", hint: "vault", category: "crime" },
    { sentence: "steal diamond necklace from museum", hint: "diamond", category: "crime" },
    { sentence: "replace security guard with mannequin", hint: "security", category: "crime" },
    { sentence: "steal getaway car from police lot", hint: "getaway", category: "crime" },
    { sentence: "hack casino slot machine jackpot", hint: "casino", category: "crime" },
    { sentence: "steal painting from art gallery", hint: "painting", category: "crime" },
    { sentence: "replace evidence with rubber ducks", hint: "evidence", category: "crime" },
    { sentence: "steal crown jewels from tower", hint: "crown", category: "crime" },
    { sentence: "hack prison security door controls", hint: "prison", category: "crime" },
    { sentence: "steal safe from behind painting", hint: "safe", category: "crime" },
    { sentence: "replace fingerprints with cat paws", hint: "fingerprints", category: "crime" },
    { sentence: "steal gold bars from underground vault", hint: "gold", category: "crime" },
    { sentence: "hack alarm system with phone", hint: "phone", category: "crime" },
    { sentence: "steal treasure map from pirates", hint: "treasure", category: "crime" },
    { sentence: "replace wanted poster with selfie", hint: "wanted", category: "crime" },
    { sentence: "steal secret documents from office", hint: "documents", category: "crime" },
    { sentence: "hack security cameras in building", hint: "cameras", category: "crime" },
    { sentence: "steal master key from janitor", hint: "janitor", category: "crime" },
    { sentence: "replace padlock with chocolate lock", hint: "padlock", category: "crime" },
  ],
  animals: [
    { sentence: "steal penguin from zoo exhibit", hint: "penguin", category: "animals" },
    { sentence: "replace guard dog with stuffed toy", hint: "guard", category: "animals" },
    { sentence: "steal parrot that knows password", hint: "parrot", category: "animals" },
    { sentence: "hack pet store automatic feeder", hint: "feeder", category: "animals" },
    { sentence: "steal racing horse from stable", hint: "horse", category: "animals" },
    { sentence: "replace aquarium fish with rubber ducks", hint: "aquarium", category: "animals" },
    { sentence: "steal carrier pigeon with message", hint: "pigeon", category: "animals" },
    { sentence: "hack animal shelter security system", hint: "shelter", category: "animals" },
    { sentence: "steal monkey from circus performance", hint: "monkey", category: "animals" },
    { sentence: "replace cat food with gourmet meal", hint: "gourmet", category: "animals" },
    { sentence: "steal snake from reptile exhibit", hint: "snake", category: "animals" },
    { sentence: "hack wildlife sanctuary drone patrol", hint: "sanctuary", category: "animals" },
    { sentence: "steal hamster wheel power generator", hint: "hamster", category: "animals" },
    { sentence: "replace elephant bath water with juice", hint: "elephant", category: "animals" },
    { sentence: "steal goldfish from dentist office", hint: "goldfish", category: "animals" },
    { sentence: "hack dog show judging computer", hint: "show", category: "animals" },
    { sentence: "steal bee honey from protected hive", hint: "bee", category: "animals" },
    { sentence: "replace bird seed with glitter", hint: "seed", category: "animals" },
    { sentence: "steal dolphin training whistle", hint: "dolphin", category: "animals" },
    { sentence: "hack cat door with remote control", hint: "door", category: "animals" },
  ],
  travel: [
    { sentence: "steal passport stamps from airport", hint: "passport", category: "travel" },
    { sentence: "replace airplane food with home cooking", hint: "airplane", category: "travel" },
    { sentence: "hack hotel room key card system", hint: "hotel", category: "travel" },
    { sentence: "steal luggage from baggage carousel", hint: "luggage", category: "travel" },
    { sentence: "replace road signs with wrong directions", hint: "road", category: "travel" },
    { sentence: "steal cruise ship captains hat", hint: "cruise", category: "travel" },
    { sentence: "hack airport departure board display", hint: "departure", category: "travel" },
    { sentence: "steal compass from explorer backpack", hint: "compass", category: "travel" },
    { sentence: "replace train horn with bicycle bell", hint: "train", category: "travel" },
    { sentence: "steal map from tourist information center", hint: "tourist", category: "travel" },
    { sentence: "hack rental car gps navigation", hint: "rental", category: "travel" },
    { sentence: "steal lifeboat from luxury yacht", hint: "lifeboat", category: "travel" },
    { sentence: "replace ferry horn with duck sound", hint: "ferry", category: "travel" },
    { sentence: "steal souvenir from gift shop secretly", hint: "souvenir", category: "travel" },
    { sentence: "hack bus route display panel", hint: "bus", category: "travel" },
    { sentence: "steal hot air balloon basket", hint: "balloon", category: "travel" },
    { sentence: "replace taxi meter with stopwatch", hint: "taxi", category: "travel" },
    { sentence: "steal lighthouse lamp at night", hint: "lighthouse", category: "travel" },
    { sentence: "hack cable car speed controls", hint: "cable", category: "travel" },
    { sentence: "steal boarding pass from first class", hint: "boarding", category: "travel" },
  ],
  education: [
    { sentence: "steal answer key from teachers desk", hint: "answer", category: "education" },
    { sentence: "hack school wifi password system", hint: "school", category: "education" },
    { sentence: "replace textbook pages with comics", hint: "textbook", category: "education" },
    { sentence: "steal chalk from every classroom", hint: "chalk", category: "education" },
    { sentence: "hack university grade portal", hint: "university", category: "education" },
    { sentence: "replace test paper with blank sheets", hint: "test", category: "education" },
    { sentence: "steal projector from lecture hall", hint: "projector", category: "education" },
    { sentence: "hack library computer booking system", hint: "booking", category: "education" },
    { sentence: "steal science lab experiment results", hint: "science", category: "education" },
    { sentence: "replace whiteboard markers with crayons", hint: "whiteboard", category: "education" },
    { sentence: "steal trophy from school showcase", hint: "trophy", category: "education" },
    { sentence: "hack cafeteria menu display screen", hint: "cafeteria", category: "education" },
    { sentence: "replace school mascot with rubber duck", hint: "duck", category: "education" },
    { sentence: "steal debate competition notes", hint: "debate", category: "education" },
    { sentence: "hack student council election votes", hint: "election", category: "education" },
    { sentence: "steal gym equipment from sports room", hint: "gym", category: "education" },
    { sentence: "replace morning assembly song with rap", hint: "assembly", category: "education" },
    { sentence: "steal globe from geography classroom", hint: "globe", category: "education" },
    { sentence: "hack chemistry lab door access code", hint: "chemistry", category: "education" },
    { sentence: "steal art supplies from studio room", hint: "studio", category: "education" },
  ],
};

// Flat array of all missions for random selection
export const missions = Object.values(missionsByCategory).flat();

// Export categories list
export const categories = Object.keys(missionsByCategory);
